### ISSUE TITLE
Working directory for cmdrunner?

### ISSUE THREAD

**Issue by divan** [wtfutil/wtf#1293]
Hey, is there a way to specify the working dir for command run by `cmdrunner` module?

My use case is showing some stats of outdated dependencies in a few working dirs with source code. Most tools that can analyze dependencies must be run from the project's directory. Am I overlooking something or there is no way to specify working dir at the moment?

**Comment by Seanstoppable** [comment]
That is an interesting thought.
A few things I can think of:
1. Wrap it in a shell script and have the shell script handle going to the appropriate directory before calling the command.
2. Have cmdrunner automatically parse a path if present and go to the directory and execute the command
3. Include a working_dir config option that cmdrunner will go to the directory and execute the command

1. Should be doable now
2. Seems maybe too much magic/I definately pause to think about unintended side effects
3. Seems straightforward, intentional by the person setting up the command and backwards compatible.

**Comment by divan** [comment]
Right, I think specifying working_dir is pretty common for running external commands. Systemd [has it](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=), Go's os.Cmd type [has it](https://pkg.go.dev/os/exec#Cmd), cron, well, doesn't have, but it doesn't have any configuration for commands at all.

Re 2, I think no need to automatically parsing path - it's either default, or user specified. That'll work.
