### ISSUE TITLE
Docker client version is too new

### ISSUE THREAD

**Issue by boomseklecki** [wtfutil/wtf#1603]
Getting error from docker module 'client version 1.42 is too new. Maximum supported API version is 1.41'. Tried updating docker daemon. Tried passing DOCKER_API_VERSION environment variable in Dockerfile.

<img width="251" alt="Screenshot 2023-06-19 at 9 54 15 PM" src="https://github.com/wtfutil/wtf/assets/54333644/5afbf8e4-fdcf-455e-84ae-af5258438136">

**Comment by gokul656** [comment]
This is due to the `github.com/docker/docker/client` pkg itself. And even if you're able to make a workaround by setting `DOCKER_API_VERSION` or by using `client.WithAPIVersionNegotiation()`. I'm not sure whether you can connect to the Docker host from within a container. Kindly try running using binary.
