### ISSUE TITLE
Allow Multiple Instances of cmdRunner

### ISSUE THREAD

**Issue by bad-hombres** [wtfutil/wtf#181]
### Feature Request
Allow for multiple instances of cmdRunner

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | probably

#### Summary
I would like to be able to run multiple instances of the cmdRunner module

**Comment by senorprogrammer** [comment]
This sort of feature's been asked for a lot. I have a plan to re-implement how config is done, and one of the side effects of that plan is that multiple instances of the same module should be possible. 

_However_, I don't know when that will be. I want to get bugs fixed first and add a few more modules that I want. No promises on a timeline.

**Comment by varac** [comment]
That's a truly missing feature, thanks in advance for implementing!

**Comment by iafan** [comment]
Would  be nice to see this happen. One approach would be to introduce a new `plugin: xxxxx` key as a configuration property for a plugin (on the same level where you have `enabled: true`). If such a key exists, it would be used to determine which plugin to use, otherwise, a parent key would be used as a plugin name. This would make configs backward-compatible.

One quick hack I quickly did in my instance is I created multiple versions of the cmdrunner plugin (cmdrunner2, cmdrunner3) — it's a very quick patch that gives one an ability to use multiple 'slots' for the plugin.

**Comment by senorprogrammer** [comment]
Thanks for posting this example, I like this approach quite a lot. I'm going to have to think about the implementation a bit from a backwards-compatibility perspective but this seems quite sound.

**Comment by Seanstoppable** [comment]
I've put together a quick PoC of another methodology. Effectively, adding a delimiter to the config key, enforcing uniqueness, but keeping things perhaps a bit simpler.
At the very least, should highlight some of the areas that would potentially be touched, with an example plugin.
It also modifies config a bit, drying up some lookups vs everything using global config. Important because one way or another we need to clean up all the `plugin_name` global lookups.
https://github.com/wtfutil/wtf/pull/388

**Comment by chross** [comment]
hey @Seanstoppable, could you provide a working binary with your code? I really want to try this out as I need multiple instancea of textfile and cmdrunner.

**Comment by Seanstoppable** [comment]
@chross A lot of the modules need updating in order to work (config loading in particular). I've slowly been going through modules to make the transition. I'll put cmdrunner and textfile near the top of the list, since the former is related to this ticket.

**Comment by chross** [comment]
@Seanstoppable sounds great. Really looking forward to this.

**Comment by senorprogrammer** [comment]
With this PR https://github.com/wtfutil/wtf/pull/418 this is now possible. Documentation will be forthcoming.
