### ISSUE TITLE
Cannot find config.yml file

### ISSUE THREAD

**Issue by EnigmaDX** [wtfutil/wtf#351]
#### What problem are you having and how can we help?
I have tried searching but I can't seem to find the config.yml file as stated in the configuration guidelines (`~/.config/wtf/config.yml`). Is it hidden in a particular directory?

**Comment by senorprogrammer** [comment]
I'm not clear on what you mean about a `github.com` directory. The compiled `wtf` binary should be writing its default config file into `~/.config/wtf/config.yml`, which is the one you want to edit. In the `go/src/github.com/wtfutil/wtf/` directory in your GOPATH, there's no `config.yml` because that's just the source (if I understand correctly what you're implying above; apologies if I've confused that).

**Comment by EnigmaDX** [comment]
You are right; I do have the `go/src/github.com/wtfutil/wtf/` path, in which the `config.yml` file is not found. I see the `~/.config/wtf/config.yml` path in terminal after I run `make install` and `make run`, but I cannot find it when I open the `wtf/` directory. So now I want to know how I can obtain the `config.yml` file?

**Comment by senorprogrammer** [comment]
I think we're going a bit in circles here. Can I ask what it is you're trying to do, specifically?

**Comment by senorprogrammer** [comment]
You can do that of course, lots of people have. It's in your `~/.config/wtf/config.yml`. To get there, in a new terminal window, do the following:

```
$> cd
$> cd .config/wtf
$> vi config.yml

I believe you're confusing the `wtf` Go project directory with the `wtf` configuration directory. These are not the same thing. The difference will be something like this:

```
Go directory: ~/go/github.com/wtfutil/wtf/
Config directory: ~/.config/wtf/
```
Makes sense?

**Comment by senorprogrammer** [comment]
Gonna close this as a solved issue. If you have any other questions about config, feel free to ask.

**Comment by EnigmaDX** [comment]
Thank you for helping me. I found the config file at long last
