### ISSUE TITLE
Supporting a transparent background 

### ISSUE THREAD

**Issue by rusdevops** [wtfutil/wtf#528]
## What should it do?
**Feature**: By default background color for applications and for each cell should be transparent
I like ❤️ using terminal and my favorite color theme is one-gnome-terminal 🎨
https://github.com/denysdovhan/one-gnome-terminal
It would be cool to get this feature 👍

**Comment by rusdevops** [comment]
I added patrons to your development 🔫

**Comment by Seanstoppable** [comment]
Does gnome terminal not have transparency? Or does wtfutil not work with the transparency levels? On OSX, wtfutil respects my terminal's background color (including transparency) by default.

**Comment by senorprogrammer** [comment]
Sounds like this might be a place the documentation could be improved for cases where it does work (i.e. describing how to make it work). For installs where it doesn't work, I think this issue/investigation is still valid. Easy transparency for all would be very nice to have.

**Comment by Seanstoppable** [comment]
I was actually looking at cell this weekend. From what I can tell looking at `tcell`, the default is to just be whatever the terminal has set:
https://github.com/gdamore/tcell/blob/de7e78efa4a71b3f36c7154989c529dbdf9ae623/color.go#L31-L33, and tview calls out in a few places that this should mean transparent, so that by default a new object will just have the color properties of the underlying object https://github.com/rivo/tview/search?q=transparent&unscoped_q=transparent

Since the terminal is the underlying rendering item, it seems like that is the layer that ultimately is going to control transparency, as long as tcell/tview do (and they seem to).

I'll test out explicitly on an Ubuntu 18 VM at some point this week.

**Comment by Seanstoppable** [comment]
Huh, weird, on linux, we definitely is straight up black background.
I seem to have something that gives transparency on load.
Note that I also found https://github.com/rivo/tview/issues/314, which seems to indicate that `ColorDefault` isn't strictly intended for transparency and some of the things we do may look weird. 

Example, with my changes, anything scrollable currently gives a bleed effect and highlightable items do not work right either.

![VirtualBox_Ubuntu 18 04_20_08_2019_22_12_58](https://user-images.githubusercontent.com/1523955/63397176-b83d1680-c397-11e9-8212-4606d7ed6a93.png)

I'll try to put together a reasonable branch for further proding.

**Comment by Seanstoppable** [comment]
Here is the PR. This looks ok with the default config (and fixes the problems mentioned above), but I can't vouch that everything works/looks 100% ok.

**Comment by senorprogrammer** [comment]
[This PR](https://github.com/wtfutil/wtf/pull/536) has been merged. It would be helpful if anyone on Linux could give `master` a try and let us know how it's working .

**Comment by rusdevops** [comment]
It works perfectly

**Comment by senorprogrammer** [comment]
Great, thanks for confirming.
