### ISSUE TITLE
GItHub Modile - API scope?

### ISSUE THREAD

**Issue by alexfornuto** [wtfutil/wtf#691]
## How can we help?
I'd like to know exactly what scope I need to define for the access token I create for the GitHub module.

## How I can help.
I'd be happy to update the documentation once this is defined.

**Comment by senorprogrammer** [comment]
The easiest is just to enable the complete `repo` scope. An update to the docs would be awesome.

**Comment by alexfornuto** [comment]
Easiest yes, but not the safest. Who knows what permissions this module _needs_?

**Comment by felicianotech** [comment]
Here's the data I put together:

You can create a GitHub token with absolutely no permissions checked off, and use the GitHub module for public projects without any issue.

![FireShot Capture 027 - Edit personal access token - github com](https://user-images.githubusercontent.com/6017470/66942146-6bcc2b00-f016-11e9-8924-c943f10d3b44.png)

Now, in the "repos" section of the permissions list, it's broken down to individual permissions of *private projects* specifically, but that doesn't matter. In order to use the GitHub module with private repos, the top-level "repos" checkbox for the entire section needs to be clicked. Without it, you'll get a 404 in the dashboard.

**Comment by senorprogrammer** [comment]
Nice work. For private repos, the `repo:invite` permission is unnecessary, we don’t display that. So top-level `repo` minus that makes sense.

**Comment by felicianotech** [comment]
True but the top-level "repo" permission includes it. If you deselect "repo:invite" (which sometimes you can't) and save the permissions, reload the page and you'll see that it's selected again.
