### ISSUE TITLE
Pocket widget

### ISSUE THREAD

**Issue by 3mard** [wtfutil/wtf#713]
## What should it do?
Create a widget to integrate with Pocket apis

Pocket allows you to save articles and read them later, useful when you want to save stuff to read them while you are on commute (and thus the name ) 

https://getpocket.com/developer/docs/v3/retrieve

**Comment by 3mard** [comment]
If approved I'd like to take a shot at this :)

**Comment by senorprogrammer** [comment]
Sounds good 👍

**Comment by StanczakDominik** [comment]
How do you envision this working? A list of recently saved articles, with links?

**Comment by 3mard** [comment]
Similar to the feed reader
List links that have been read, and then ones to be read, sort them (by read unread) and open them in the browser if needed.

I've almost finished this but couldn't push it as I am traveling at the moment 
Will push it soon

**Comment by michaelMinar** [comment]
This seems like an awesome widget! unfortunately, I can't quite get it working in my setup. I get an auth url posted instead of articles, and when i go the url to try and authorize the app with pocket i get an error when it tries to redirect to localhost. Is this officially supported? Any ideas on how to fix the auth issue?

**Comment by senorprogrammer** [comment]
Given that this issue is closed, do you want to open a new one for this issue? I don't use Pocket myself, but perhaps someone who does will see it and be able to provide help. Feel free to link it to this issue for continuity.
