### ISSUE TITLE
Colors does not work under gnu screen

### ISSUE THREAD

**Issue by Hubbitus** [wtfutil/wtf#822]
Under gnu screen:
![image](https://user-images.githubusercontent.com/720349/72477022-b7ea5f80-37ff-11ea-8f29-c5330262612d.png)
Same under just `yakuake` terminal:
![image](https://user-images.githubusercontent.com/720349/72477115-e5370d80-37ff-11ea-8208-3d7424abf466.png)

```
$ echo $TERM
screen-256color
$ ./wtfutil --version
0.25.0
```

**Comment by Seanstoppable** [comment]
@Hubbitus I've been able to replicate some of this, but not quite the same.
Do you mind sharing:
Version of screen (Should be `screen -v`)
$TERM outside of screen
OS/version

Based on previous color related things, it could be one of our dependencies, or could be some unexpected setup issue in a combination of projects.

**Comment by Hubbitus** [comment]
```
$ screen -v
Screen version 4.06.02 (GNU) 23-Oct-17
```

```
$ echo $TERM
xterm-256color
```
That's same in screen session.

I use Fedora 31

**Comment by Seanstoppable** [comment]
In screen, can you try `export COLORTERM=xterm-256color`?

**Comment by Hubbitus** [comment]
`COLORTERM=xterm-256color ./wtfutil` works!
Is it possible use default `TERM` instead?

**Comment by Seanstoppable** [comment]
Still trying to figure out root cause.
I am confused, because `truecolor` is both the value in screen, and the value in my regular terminal, and my regular terminal is fine.
Possiblt has to do with this code way down in tcell
https://github.com/gdamore/tcell/blob/1922b3786eaefecbba6fd8e11dbfd3531fad7a54/terminfo/terminfo.go#L718

**Comment by Seanstoppable** [comment]
So, after a bunch of reading, this is because that screen does not support truecolor at this time. This may be supported in the latest head, but not in an official release
One option is to add `setenv COLORTERM ""` to your `.screenrc` in order for screen to unset the variable that is being set by your base terminal.

https://gist.github.com/XVilka/8346728

**Comment by Seanstoppable** [comment]
HEAD version of screen has better support, though borders seem weird for some reason

<img width="714" alt="Screen Shot 2020-02-23 at 11 47 08 AM" src="https://user-images.githubusercontent.com/1523955/75116046-50aba080-5632-11ea-9ccb-a0dd770eea06.png">

**Comment by senorprogrammer** [comment]
Closing as stale.
