### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by AshutoshSajan** [wtfutil/wtf#910]
while installing from source i am getting this error

build github.com/wtfutil/wtf: cannot load github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2

**Comment by jonhadfield** [comment]
In tag v0.4.1 of github.com/googleapis/gnostic they changed the case of OpenAPIv2 to openapiv2. I suspect that's the root cause but, as I'm no expert on modules, will need to leave to someone else (or when I get time).
FWIW, I just did a manual upgrade of k8s.io/client-go and now I can't build wtf either :(

**Comment by senorprogrammer** [comment]
Hi @AshutoshSajan is this still an issue for you?

**Comment by AshutoshSajan** [comment]
I didn't found the solution for that and then I never tried to install it again. but thank you.
